#!/usr/bin/env bash

echo -e "\e[33m BEGIN commiting dotfiles\e[37m"
commitdot || echo -e "\e[31m \n commit failed..\n check network connection \e[37m"
echo -e "\e[33m ENDED commiting dotfiles\e[37m"
echo -e "\n"

cd ~/snippets && gacp update snippets

echo -e "\e[33m BEGIN commiting notes\e[37m"
notes push || echo -e "\e[31m \n commit failed..\n check network connection \e[37m"
echo -e "\e[33m END commiting notes\e[37m"

if [[ $? == 0 ]]; then
echo -e "\e[32m success! \e[37m"
fi




