#!/usr/bin/env bash

commitdotfiles() {
pushd $DOTFILES
git add nvim wezterm
git commit -am "update dotfiles $(date)"
git push || echo "push failed..check internet connection"
popd
}


commitdotfiles
