#!/usr/bin/env bash

commitdot || echo -e "\e[31m \n commit failed..\n check network connection \e[37m"
notes push || echo -e "\e[31m \n commit failed..\n check network connection \e[37m"
if [[ $0 == 0 ]]; then
echo -e "\e[32 success! \e[37m"
fi




