#!/usr/bin/env bash

session=$(sesh list  | fzf)
# Old buggy way:
# kitty --directory "$1" tmuxinator start my_project &

# The Fix: Add a minor sleep inside an explicit execution string
tmuxinator start $session
